#!/usr/bin/env node

process.title = 'scaffold';

var scaffold = require('./dist/');

var argv = require('yargs')
            .usage('Usage: $0 <command> [options]')
            .argv;

scaffold.run(argv, function() {
    watcher(argv);
});